// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: packet.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BLESendPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*BLESendPacket_Placeholder
	//	*BLESendPacket_GetWifi
	//	*BLESendPacket_WifiConnectInfo
	//	*BLESendPacket_Nonce
	Type isBLESendPacket_Type `protobuf_oneof:"type"`
}

func (x *BLESendPacket) Reset() {
	*x = BLESendPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLESendPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLESendPacket) ProtoMessage() {}

func (x *BLESendPacket) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLESendPacket.ProtoReflect.Descriptor instead.
func (*BLESendPacket) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

func (m *BLESendPacket) GetType() isBLESendPacket_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *BLESendPacket) GetPlaceholder() *Placeholder {
	if x, ok := x.GetType().(*BLESendPacket_Placeholder); ok {
		return x.Placeholder
	}
	return nil
}

func (x *BLESendPacket) GetGetWifi() *GetWiFi {
	if x, ok := x.GetType().(*BLESendPacket_GetWifi); ok {
		return x.GetWifi
	}
	return nil
}

func (x *BLESendPacket) GetWifiConnectInfo() *WiFiConnectInfo {
	if x, ok := x.GetType().(*BLESendPacket_WifiConnectInfo); ok {
		return x.WifiConnectInfo
	}
	return nil
}

func (x *BLESendPacket) GetNonce() *RegisterNonce {
	if x, ok := x.GetType().(*BLESendPacket_Nonce); ok {
		return x.Nonce
	}
	return nil
}

type isBLESendPacket_Type interface {
	isBLESendPacket_Type()
}

type BLESendPacket_Placeholder struct {
	Placeholder *Placeholder `protobuf:"bytes,1,opt,name=placeholder,proto3,oneof"`
}

type BLESendPacket_GetWifi struct {
	GetWifi *GetWiFi `protobuf:"bytes,3,opt,name=getWifi,proto3,oneof"`
}

type BLESendPacket_WifiConnectInfo struct {
	WifiConnectInfo *WiFiConnectInfo `protobuf:"bytes,4,opt,name=wifiConnectInfo,proto3,oneof"`
}

type BLESendPacket_Nonce struct {
	Nonce *RegisterNonce `protobuf:"bytes,5,opt,name=nonce,proto3,oneof"`
}

func (*BLESendPacket_Placeholder) isBLESendPacket_Type() {}

func (*BLESendPacket_GetWifi) isBLESendPacket_Type() {}

func (*BLESendPacket_WifiConnectInfo) isBLESendPacket_Type() {}

func (*BLESendPacket_Nonce) isBLESendPacket_Type() {}

type Placeholder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Placeholder) Reset() {
	*x = Placeholder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholder) ProtoMessage() {}

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{1}
}

type GetWiFi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWiFi) Reset() {
	*x = GetWiFi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWiFi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWiFi) ProtoMessage() {}

func (x *GetWiFi) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWiFi.ProtoReflect.Descriptor instead.
func (*GetWiFi) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{2}
}

type WiFiVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*WiFiData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *WiFiVector) Reset() {
	*x = WiFiVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WiFiVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiVector) ProtoMessage() {}

func (x *WiFiVector) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiVector.ProtoReflect.Descriptor instead.
func (*WiFiVector) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{3}
}

func (x *WiFiVector) GetData() []*WiFiData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WiFiData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ssid        string `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Bssid       uint64 `protobuf:"varint,2,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Channel     uint32 `protobuf:"varint,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	IsEncrypted bool   `protobuf:"varint,4,opt,name=isEncrypted,proto3" json:"isEncrypted,omitempty"`
}

func (x *WiFiData) Reset() {
	*x = WiFiData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WiFiData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiData) ProtoMessage() {}

func (x *WiFiData) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiData.ProtoReflect.Descriptor instead.
func (*WiFiData) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{4}
}

func (x *WiFiData) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WiFiData) GetBssid() uint64 {
	if x != nil {
		return x.Bssid
	}
	return 0
}

func (x *WiFiData) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *WiFiData) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

type WiFiConnectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ssid     string `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *WiFiConnectInfo) Reset() {
	*x = WiFiConnectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WiFiConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiConnectInfo) ProtoMessage() {}

func (x *WiFiConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiConnectInfo.ProtoReflect.Descriptor instead.
func (*WiFiConnectInfo) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{5}
}

func (x *WiFiConnectInfo) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WiFiConnectInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type WiFiConnectResponseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*WiFiConnectResponseInfo_Placeholder
	//	*WiFiConnectResponseInfo_Timeout
	//	*WiFiConnectResponseInfo_ConnectingToWiFi
	//	*WiFiConnectResponseInfo_ConnectedToWiFi
	//	*WiFiConnectResponseInfo_ConnectingToServer
	//	*WiFiConnectResponseInfo_FailedConnectingToServer
	Type isWiFiConnectResponseInfo_Type `protobuf_oneof:"type"`
}

func (x *WiFiConnectResponseInfo) Reset() {
	*x = WiFiConnectResponseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WiFiConnectResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiConnectResponseInfo) ProtoMessage() {}

func (x *WiFiConnectResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiConnectResponseInfo.ProtoReflect.Descriptor instead.
func (*WiFiConnectResponseInfo) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{6}
}

func (m *WiFiConnectResponseInfo) GetType() isWiFiConnectResponseInfo_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *WiFiConnectResponseInfo) GetPlaceholder() *Placeholder {
	if x, ok := x.GetType().(*WiFiConnectResponseInfo_Placeholder); ok {
		return x.Placeholder
	}
	return nil
}

func (x *WiFiConnectResponseInfo) GetTimeout() *Timeout {
	if x, ok := x.GetType().(*WiFiConnectResponseInfo_Timeout); ok {
		return x.Timeout
	}
	return nil
}

func (x *WiFiConnectResponseInfo) GetConnectingToWiFi() *ConnectingToWiFi {
	if x, ok := x.GetType().(*WiFiConnectResponseInfo_ConnectingToWiFi); ok {
		return x.ConnectingToWiFi
	}
	return nil
}

func (x *WiFiConnectResponseInfo) GetConnectedToWiFi() *ConnectedToWiFi {
	if x, ok := x.GetType().(*WiFiConnectResponseInfo_ConnectedToWiFi); ok {
		return x.ConnectedToWiFi
	}
	return nil
}

func (x *WiFiConnectResponseInfo) GetConnectingToServer() *ConnectingToServer {
	if x, ok := x.GetType().(*WiFiConnectResponseInfo_ConnectingToServer); ok {
		return x.ConnectingToServer
	}
	return nil
}

func (x *WiFiConnectResponseInfo) GetFailedConnectingToServer() *FailedConnectingToServer {
	if x, ok := x.GetType().(*WiFiConnectResponseInfo_FailedConnectingToServer); ok {
		return x.FailedConnectingToServer
	}
	return nil
}

type isWiFiConnectResponseInfo_Type interface {
	isWiFiConnectResponseInfo_Type()
}

type WiFiConnectResponseInfo_Placeholder struct {
	Placeholder *Placeholder `protobuf:"bytes,1,opt,name=placeholder,proto3,oneof"`
}

type WiFiConnectResponseInfo_Timeout struct {
	Timeout *Timeout `protobuf:"bytes,2,opt,name=timeout,proto3,oneof"`
}

type WiFiConnectResponseInfo_ConnectingToWiFi struct {
	ConnectingToWiFi *ConnectingToWiFi `protobuf:"bytes,3,opt,name=connectingToWiFi,proto3,oneof"`
}

type WiFiConnectResponseInfo_ConnectedToWiFi struct {
	ConnectedToWiFi *ConnectedToWiFi `protobuf:"bytes,4,opt,name=connectedToWiFi,proto3,oneof"`
}

type WiFiConnectResponseInfo_ConnectingToServer struct {
	ConnectingToServer *ConnectingToServer `protobuf:"bytes,5,opt,name=connectingToServer,proto3,oneof"`
}

type WiFiConnectResponseInfo_FailedConnectingToServer struct {
	FailedConnectingToServer *FailedConnectingToServer `protobuf:"bytes,6,opt,name=failedConnectingToServer,proto3,oneof"`
}

func (*WiFiConnectResponseInfo_Placeholder) isWiFiConnectResponseInfo_Type() {}

func (*WiFiConnectResponseInfo_Timeout) isWiFiConnectResponseInfo_Type() {}

func (*WiFiConnectResponseInfo_ConnectingToWiFi) isWiFiConnectResponseInfo_Type() {}

func (*WiFiConnectResponseInfo_ConnectedToWiFi) isWiFiConnectResponseInfo_Type() {}

func (*WiFiConnectResponseInfo_ConnectingToServer) isWiFiConnectResponseInfo_Type() {}

func (*WiFiConnectResponseInfo_FailedConnectingToServer) isWiFiConnectResponseInfo_Type() {}

type Timeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Timeout) Reset() {
	*x = Timeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeout) ProtoMessage() {}

func (x *Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeout.ProtoReflect.Descriptor instead.
func (*Timeout) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{7}
}

type ConnectingToWiFi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectingToWiFi) Reset() {
	*x = ConnectingToWiFi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectingToWiFi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectingToWiFi) ProtoMessage() {}

func (x *ConnectingToWiFi) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectingToWiFi.ProtoReflect.Descriptor instead.
func (*ConnectingToWiFi) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{8}
}

type ConnectedToWiFi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectedToWiFi) Reset() {
	*x = ConnectedToWiFi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectedToWiFi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedToWiFi) ProtoMessage() {}

func (x *ConnectedToWiFi) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedToWiFi.ProtoReflect.Descriptor instead.
func (*ConnectedToWiFi) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{9}
}

type ConnectingToServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectingToServer) Reset() {
	*x = ConnectingToServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectingToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectingToServer) ProtoMessage() {}

func (x *ConnectingToServer) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectingToServer.ProtoReflect.Descriptor instead.
func (*ConnectingToServer) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{10}
}

type FailedConnectingToServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Causeid int32  `protobuf:"varint,1,opt,name=causeid,proto3" json:"causeid,omitempty"`
	Cause   string `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
}

func (x *FailedConnectingToServer) Reset() {
	*x = FailedConnectingToServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailedConnectingToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedConnectingToServer) ProtoMessage() {}

func (x *FailedConnectingToServer) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedConnectingToServer.ProtoReflect.Descriptor instead.
func (*FailedConnectingToServer) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{11}
}

func (x *FailedConnectingToServer) GetCauseid() int32 {
	if x != nil {
		return x.Causeid
	}
	return 0
}

func (x *FailedConnectingToServer) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type RegisterNonce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *RegisterNonce) Reset() {
	*x = RegisterNonce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNonce) ProtoMessage() {}

func (x *RegisterNonce) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNonce.ProtoReflect.Descriptor instead.
func (*RegisterNonce) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterNonce) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

var File_packet_proto protoreflect.FileDescriptor

var file_packet_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x6e, 0x61, 0x6e, 0x6f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a,
	0x0d, 0x42, 0x4c, 0x45, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x30,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x12, 0x24, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x57, 0x69, 0x66, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x48, 0x00, 0x52, 0x07, 0x67,
	0x65, 0x74, 0x57, 0x69, 0x66, 0x69, 0x12, 0x3c, 0x0a, 0x0f, 0x77, 0x69, 0x66, 0x69, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x57, 0x69, 0x46, 0x69, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x48, 0x00, 0x52, 0x0f, 0x77, 0x69, 0x66, 0x69, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x22, 0x09, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x57, 0x69, 0x46, 0x69, 0x22, 0x32,
	0x0a, 0x0a, 0x57, 0x69, 0x46, 0x69, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x57, 0x69, 0x46,
	0x69, 0x44, 0x61, 0x74, 0x61, 0x42, 0x05, 0x92, 0x3f, 0x02, 0x10, 0x40, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x77, 0x0a, 0x08, 0x57, 0x69, 0x46, 0x69, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19,
	0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x92, 0x3f,
	0x02, 0x08, 0x20, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x73, 0x73,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x73, 0x73, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x69, 0x73, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x22, 0x4f, 0x0a, 0x0f, 0x57,
	0x69, 0x46, 0x69, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19,
	0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x92, 0x3f,
	0x02, 0x08, 0x20, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x92, 0x3f, 0x02,
	0x08, 0x40, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x98, 0x03, 0x0a,
	0x17, 0x57, 0x69, 0x46, 0x69, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x12, 0x3f, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f,
	0x57, 0x69, 0x46, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x57, 0x69, 0x46, 0x69, 0x48, 0x00, 0x52,
	0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x57, 0x69, 0x46,
	0x69, 0x12, 0x3c, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x6f,
	0x57, 0x69, 0x46, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x57, 0x69, 0x46, 0x69, 0x48, 0x00, 0x52, 0x0f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x57, 0x69, 0x46, 0x69, 0x12,
	0x45, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x12, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x18, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x48, 0x00, 0x52, 0x18, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67,
	0x54, 0x6f, 0x57, 0x69, 0x46, 0x69, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x54, 0x6f, 0x57, 0x69, 0x46, 0x69, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22,
	0x51, 0x0a, 0x18, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x61, 0x75, 0x73, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x61,
	0x75, 0x73, 0x65, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0x92, 0x3f, 0x02, 0x08, 0x20, 0x52, 0x05, 0x63, 0x61, 0x75,
	0x73, 0x65, 0x22, 0x2c, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x05, 0x92, 0x3f, 0x02, 0x08, 0x10, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData = file_packet_proto_rawDesc
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_packet_proto_rawDescData)
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_packet_proto_goTypes = []interface{}{
	(*BLESendPacket)(nil),            // 0: BLESendPacket
	(*Placeholder)(nil),              // 1: Placeholder
	(*GetWiFi)(nil),                  // 2: GetWiFi
	(*WiFiVector)(nil),               // 3: WiFiVector
	(*WiFiData)(nil),                 // 4: WiFiData
	(*WiFiConnectInfo)(nil),          // 5: WiFiConnectInfo
	(*WiFiConnectResponseInfo)(nil),  // 6: WiFiConnectResponseInfo
	(*Timeout)(nil),                  // 7: Timeout
	(*ConnectingToWiFi)(nil),         // 8: ConnectingToWiFi
	(*ConnectedToWiFi)(nil),          // 9: ConnectedToWiFi
	(*ConnectingToServer)(nil),       // 10: ConnectingToServer
	(*FailedConnectingToServer)(nil), // 11: FailedConnectingToServer
	(*RegisterNonce)(nil),            // 12: RegisterNonce
}
var file_packet_proto_depIdxs = []int32{
	1,  // 0: BLESendPacket.placeholder:type_name -> Placeholder
	2,  // 1: BLESendPacket.getWifi:type_name -> GetWiFi
	5,  // 2: BLESendPacket.wifiConnectInfo:type_name -> WiFiConnectInfo
	12, // 3: BLESendPacket.nonce:type_name -> RegisterNonce
	4,  // 4: WiFiVector.data:type_name -> WiFiData
	1,  // 5: WiFiConnectResponseInfo.placeholder:type_name -> Placeholder
	7,  // 6: WiFiConnectResponseInfo.timeout:type_name -> Timeout
	8,  // 7: WiFiConnectResponseInfo.connectingToWiFi:type_name -> ConnectingToWiFi
	9,  // 8: WiFiConnectResponseInfo.connectedToWiFi:type_name -> ConnectedToWiFi
	10, // 9: WiFiConnectResponseInfo.connectingToServer:type_name -> ConnectingToServer
	11, // 10: WiFiConnectResponseInfo.failedConnectingToServer:type_name -> FailedConnectingToServer
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	file_nanopb_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLESendPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Placeholder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWiFi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WiFiVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WiFiData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WiFiConnectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WiFiConnectResponseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectingToWiFi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectedToWiFi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectingToServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailedConnectingToServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNonce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packet_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BLESendPacket_Placeholder)(nil),
		(*BLESendPacket_GetWifi)(nil),
		(*BLESendPacket_WifiConnectInfo)(nil),
		(*BLESendPacket_Nonce)(nil),
	}
	file_packet_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*WiFiConnectResponseInfo_Placeholder)(nil),
		(*WiFiConnectResponseInfo_Timeout)(nil),
		(*WiFiConnectResponseInfo_ConnectingToWiFi)(nil),
		(*WiFiConnectResponseInfo_ConnectedToWiFi)(nil),
		(*WiFiConnectResponseInfo_ConnectingToServer)(nil),
		(*WiFiConnectResponseInfo_FailedConnectingToServer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_rawDesc = nil
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
